# Select image from https://hub.docker.com/r/_/php/
image: php:7.1

#cache:
  #paths:
  #- vendor/

test:app:
  before_script:
  # Install dependencies
    - bash ci/docker_install.sh > /dev/null
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar require nesbot/carbon=1.29.*
    - cp $CI_PROJECT_DIR/ci/memory_limit.ini /usr/local/etc/php/conf.d/memory_limit.ini
  script:
  #- phpunit --configuration phpunit_myapp.xml
  #Static analysis
    - phploc .
  #phpmd check coding style
  #- phpmd . text naming,design,unusedcode --suffixes php --ignore-violations-on-exit
  # - phpmd . text unusedcode --suffixes php --ignore-violations-on-exit --exclude vendor/*
  #checking Coding Standards with PHP Code Sniffer
  #- phpcpd .
  #Viewing Coding Standards Violations
  #
  # - phpcs --standard=PEAR --report=summary

build site:
  image: tetraweb/php
  stage: build
  script:
    - php composer.phar install
    - npm install
  artifacts:
    expire_in: 1 week
    paths:
      - build

deploy_staging:
  stage: deploy
  only:
    - dev
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav -e 'ssh -p 2424' --delete public/ ndo@94.249.131.5:/var/www/html/maintenance_stage

deploy_production:
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav -e 'ssh -p 2424' --delete build/ ndo@94.249.131.5:/var/www/html/maintenance_prod
