# Select image from https://hub.docker.com/r/_/php/
image: php:7.0

before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php composer-setup.php
- php -r "unlink('composer-setup.php');"
- composer require nesbot/carbon=1.29.*

test:app:
  script:
  #- phpunit --configuration phpunit_myapp.xml
  #Static analysis
  - phploc /build/*.php --progress --no-ansi -n 
  #phpmd check coding style
  - phpmd . text naming,design,unusedcode --suffixes php --ignore-violations-on-exit
  #checking Coding Standards with PHP Code Sniffer
  #- phpcpd .
  #Viewing Coding Standards Violations
  # - phpcs --standard=PEAR --report=summary
